

CREATE TABLE temp_domain (
  id varchar(255) default NULL,
  name varchar(255) default NULL,
  domain varchar(255) default NULL
);



INSERT INTO temp_domain VALUES ('0-1-1','Meat Quality','class');
INSERT INTO temp_domain VALUES ('0-1-2','Health','class');
INSERT INTO temp_domain VALUES ('0-1-3','Exterior','class');
INSERT INTO temp_domain VALUES ('0-1-4','Production','class');
INSERT INTO temp_domain VALUES ('0-1-5','Reproduction','class');
INSERT INTO temp_domain VALUES ('0-1-1-1-1','abdominal fat','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-2','backfat [average] thickness','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-204','backfat [average] thickness','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-290','backfat [average] thickness','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-171','backfat at first rib','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-261','backfat at first rib [measured at 14 weeks of age]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-262','backfat at first rib [measured at 26 weeks of age]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-3','backfat above muscle dorsi','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-4','backfat thickness at last rib','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-291','backfat depth at last rib','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-263','backfat at last rib [measured at 14 weeks of age]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-264','backfat at last rib [measured at 26 weeks of age]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-5','backfat at P2 position','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-6','backfat at shoulder','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-7','backfat at tenth rib','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-8','backfat between 3th and 4th rib','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-306','backfat between 6th and 7th rib','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-9','backfat depth at max. mus. depth','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-10','backfat at last lumbar','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-308','backfat between the last 3th and 4th lumbar','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-265','backfat at last lumbar [measured at 14 weeks of age]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-266','backfat at last lumbar [measured at 26 weeks of age]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-289','backfat at rump','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-11','backfat middle','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-12','backfat side','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-188','backfat [13 weeks of age]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-189','backfat [17 weeks of age]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-190','backfat [22 weeks of age]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-191','backfat [40 kg live weight]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-192','backfat [60 kg live weight]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-13','fat percentage in carcass','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-14','fat area','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-307','fat weight [total]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-15','intermuscular fat weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-16','intramuscular fat percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-221','backfat weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-172','leaf fat weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-301','leaf fat percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-302','intestinal fat weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-303','intestinal fat percent','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-304','internal fat ratio','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-305','fat ratio [percentage]','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-222','Percentage of backfat and leaf fat in carcass','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-17','marbling','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-18','residual fatty acids','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-19','side fat','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-20','subcutaneous fat depth','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-21','subcutaneous fat weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-22','sum of all fatty acids','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1-23','total lipid','trait');
INSERT INTO temp_domain VALUES ('0-1-1-2-24','color a','trait');
INSERT INTO temp_domain VALUES ('0-1-1-2-25','color b','trait');
INSERT INTO temp_domain VALUES ('0-1-1-2-26','color L','trait');
INSERT INTO temp_domain VALUES ('0-1-1-2-27','hue','trait');
INSERT INTO temp_domain VALUES ('0-1-1-2-28','meat brightness','trait');
INSERT INTO temp_domain VALUES ('0-1-1-2-29','light reflection','trait');
INSERT INTO temp_domain VALUES ('0-1-1-2-173','color score','trait');
INSERT INTO temp_domain VALUES ('0-1-1-2-201','Hematin pigmentation','trait');
INSERT INTO temp_domain VALUES ('0-1-1-3-30','pH 24 hours post mortem (loin)','trait');
INSERT INTO temp_domain VALUES ('0-1-1-3-200','pH 24 hours post mortem (ham)','trait');
INSERT INTO temp_domain VALUES ('0-1-1-3-31','pH 45 minutes post mortem','trait');
INSERT INTO temp_domain VALUES ('0-1-1-3-311','pH for Biceps Femoris','trait');
INSERT INTO temp_domain VALUES ('0-1-1-3-312','pH for Semispinalis Dorsi','trait');
INSERT INTO temp_domain VALUES ('0-1-1-3-313','pH for Longissmus Dorsi','trait');
INSERT INTO temp_domain VALUES ('0-1-1-4-32','conductivity 45 minutes post mortem','trait');
INSERT INTO temp_domain VALUES ('0-1-1-4-33','conductivity 24 hours post mortem','trait');
INSERT INTO temp_domain VALUES ('0-1-1-29-202','Creatine-phospho-kinase test','trait');
INSERT INTO temp_domain VALUES ('0-1-1-30-203','Rigor mortis','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-34','average instron (star probe) force','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-35','chew score','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-36','cooking loss','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-37','drip loss','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-208','Number of white fibers','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-209','Percentage of white fibers','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-210','Diameter of white fibers','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-211','R-value','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-213','R-value / Diameter of white fibers','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-214','Lactate / Diameter of white fibers','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-38','fiber type 1','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-39','fiber type 2 ratio','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-40','firmness','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-41','percent cooking loss','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-42','shear force','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-43','tenderness score','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-44','water holding capacity','trait');
INSERT INTO temp_domain VALUES ('0-1-1-5-297','Moisture Content','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-45','androstenone, laboratory','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-46','average glycogen','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-47','average glycolytic potential','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-48','average lactate','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-49','cholesterol','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-50','indole, laboratory','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-52','muscle moisture percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-53','muscle protein percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-54','pork flavour in fat','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-55','pork flavour in lean','trait');
INSERT INTO temp_domain VALUES ('0-1-1-6-56','skatole, laboratory','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-57','androstenone, taste panel','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-58','skatole, taste panel','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-59','subjective abnormal flavour in fat','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-60','subjective abnormal flavour in lean','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-61','subjective boar flavor in fat','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-62','subjective boar flavor in lean','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-63','subjective chew score','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-64','subjective flavor score','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-65','subjective juiciness score','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-66','subjective pork flavor in fat','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-67','subjective pork flavor in lean','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-68','subjective tenderness score','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-174','subjective off-flavor score','trait');
INSERT INTO temp_domain VALUES ('0-1-1-7-175','intensity taste','trait');
INSERT INTO temp_domain VALUES ('0-1-1-8-69','subjective abnormal odor','trait');
INSERT INTO temp_domain VALUES ('0-1-1-8-70','subjective overall acceptibility score','trait');
INSERT INTO temp_domain VALUES ('0-1-1-8-71','subjective pork odour','trait');
INSERT INTO temp_domain VALUES ('0-1-1-8-176','smell intensity','trait');
INSERT INTO temp_domain VALUES ('0-1-1-8-177','smell intensity - fat','trait');
INSERT INTO temp_domain VALUES ('0-1-1-8-178','Sub-acid smell','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-72','body mass index','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-73','bone weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-310','bone percent','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-247','bone/lean meat ratio in ham','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-248','Lean meat + bone in ham + back','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-281','Lean mass (weight)','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-249','Lean meat + bone in back','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-279','Backfat percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-280','Fat-cut percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-74','belly weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-288','belly percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-75','carcass length','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-76','carcass weight (cold)','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-293','Carcass yield','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-283','carcass fat free weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-77','hot carcass weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-223','dressing percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-78','diaphragm weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-79','eye muscle depth','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-80','Feet weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-81','foreloin weight post-dissection','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-82','foreloin weight pre-dissection','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-83','head weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-84','lean percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-277','ham percent','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-85','lean thickness between 3th and 4th rib','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-86','loin eye area','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-295','Longissimus muscle length','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-87','muscle + diaphragm weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-88','muscle weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-215','Loin weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-278','Loin percent','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-216','Ham weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-217','Estimated carcass lean content','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-218','Loin and ham percentage in carcass','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-219','Shoulder weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-220','Loin muscle depth','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-296','Loin and belly cut','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-89','skin weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-309','skin percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-198','skin thickness','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-90','Trimmed whole-sale product / live weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-91','Trimmed whole-sale product / carcass weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-9-282','Heart weight','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-92','fat androstenone level','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-267','fat androstenone level at 100 days of age','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-268','fat androstenone level at 120 days of age','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-269','fat androstenone level at 140 days of age','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-270','fat androstenone level at 160 days of age','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-93','Linoleic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-94','heptadecanoic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-229','Linolenic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-230','Myristic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-231','Palmitic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-232','Palmitoleic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-179','Heptadecanoic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-250','Stearic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-251','Oleic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-252','7-Octadecenoic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-253','Eicosenoic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-254','Eicosadienoic acid percentage','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-233','Average chain length','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-234','Double-bond index','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-235','Unsaturated index','trait');
INSERT INTO temp_domain VALUES ('0-1-1-10-236','Peroxidability index','trait');
INSERT INTO temp_domain VALUES ('0-1-2-11-95','Salmonella count in feces day 1 post infection','trait');
INSERT INTO temp_domain VALUES ('0-1-2-11-96','Salmonella count in feces day 7 post infection','trait');
INSERT INTO temp_domain VALUES ('0-1-2-11-97','Salmonella count in liver','trait');
INSERT INTO temp_domain VALUES ('0-1-2-11-98','Salmonella count in spleen','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-99','number of leucocytes','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-100','mitogen-induced proliferation','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-271','PWM-induced proliferation','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-272','conA-induced proliferation','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-273','spontenous proliferation','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-101','pre/post-vaccination levels of IgG to K88 antigen','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-102','specific IgG response to E. coli O149 antigen','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-103','post-stress mitogen induced IL-2 activity','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-104','stress induced neutrophils numbers alteration','trait');
INSERT INTO temp_domain VALUES ('0-1-2-12-105','stress induced leukocyte proliferation.','trait');
INSERT INTO temp_domain VALUES ('0-1-2-13-106','resistance to E.coli K88 infection','trait');
INSERT INTO temp_domain VALUES ('0-1-2-13-274','Anti-K88 E.coli IgG levels','trait');
INSERT INTO temp_domain VALUES ('0-1-2-13-275','Anti-O149 E.coli IgG levels','trait');
INSERT INTO temp_domain VALUES ('0-1-2-13-276','Anti-O149 E.coli IgG level response','trait');
INSERT INTO temp_domain VALUES ('0-1-2-13-224','Small intestinal Escherichia coli F18 receptor','trait');
INSERT INTO temp_domain VALUES ('0-1-2-13-51','resistance to psuedorabies virus infection','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-107','ACTH basal level','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-237','ACTH response to stress','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-238','ACTH response to stress','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-108','Basal cortisol levels','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-239','post-stress cortisol levels','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-240','post-stress cortisol levels','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-241','Basal glucose levels','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-242','Glucose level response to stress','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-243','Glucose level variations','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-244','Locomotion','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-245','Exploration','trait');
INSERT INTO temp_domain VALUES ('0-1-3-14-109','neuroendocrine responses','trait');
INSERT INTO temp_domain VALUES ('0-1-3-15-110','black vs white color','trait');
INSERT INTO temp_domain VALUES ('0-1-3-15-111','spots','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-112','body length','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-294','thoracic vertebra number','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-197','total vertebra number','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-246','vertebra distance','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-113','claws length front inside','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-114','claws length front outside','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-115','claws length hind inside','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-116','claws length hind outside','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-117','feet and legs score','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-118','feet score front','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-119','feet score rear','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-120','hair (amount)','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-121','height','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-122','joint abnormalities','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-123','joint leasions','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-124','leg length','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-125','leg pastern front','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-126','leg pastern hind','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-127','leg score front','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-128','leg score hind','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-129','leg set view','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-130','leg torsion front','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-131','leg torsion hind','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-132','legs angularity front','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-133','legs angularity hind','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-292','Circumference of cannon bone','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-134','femur dimensions','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-135','osteochondrosis','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-136','lob ear','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-137','nose score','trait');
INSERT INTO temp_domain VALUES ('0-1-3-16-138','swelling of joints','trait');
INSERT INTO temp_domain VALUES ('0-1-3-17-139','longevity (sow)','trait');
INSERT INTO temp_domain VALUES ('0-1-3-18-140','scrotal hernia','trait');
INSERT INTO temp_domain VALUES ('0-1-3-18-141','rhinitis','trait');
INSERT INTO temp_domain VALUES ('0-1-4-19-142','feed intake 35 to 55 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-19-143','feed intake 55 to 80 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-28-195','length of small intestine','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-144','average daily gain','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-145','average daily gain 35 to 55 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-146','average daily gain 55 to 80 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-205','average daily gain weaning to 25 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-225','average daily gain weaning to 55 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-206','average daily gain 25 to 90 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-207','average daily gain during the entire life.','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-147','average daily gain birth to end of test','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-193','average daily gain birth to 30 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-194','average daily gain birth to 70 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-148','average daily gain on weaning','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-149','average daily gain on test','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-185','average daily gain (birth to 3 weeks)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-226','average daily gain (3 to 5 weeks)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-227','average daily gain (5 to 7 weeks)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-228','average daily gain (7 to 9 weeks)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-186','average daily gain (3-10 weeks)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-196','average daily gain (4-13 weeks)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-187','average daily gain (10-22 weeks)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-259','average daily gain (8-18 weeks)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-260','average daily gain (18-26 weeks)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-298','average daily gain (birth-60 days)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-299','average daily gain (60-160 days)','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-153','body weight at birth','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-154','body weight at slaughter','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-284','Age at slaughter','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-155','body weight at 16 days','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-180','body weight at 3 weeks of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-199','body weight at weaning','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-256','body weight at 4 weeks of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-257','body weight at 8 weeks of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-181','body weight at 10 weeks of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-182','body weight at 13 weeks of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-183','body weight at 17 weeks of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-184','body weight at 22 weeks of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-255','body weight at 25 weeks of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-258','body weight at 26 weeks of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-20-300','body weight at 60 days of age','trait');
INSERT INTO temp_domain VALUES ('0-1-4-21-150','feed conversion ratio','trait');
INSERT INTO temp_domain VALUES ('0-1-4-21-151','feed conversion ratio 35 to 55 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-4-21-152','feed conversion ratio 55 to 80 kg','trait');
INSERT INTO temp_domain VALUES ('0-1-5-23-156','total number born','trait');
INSERT INTO temp_domain VALUES ('0-1-5-23-157','total number born alive','trait');
INSERT INTO temp_domain VALUES ('0-1-5-23-158','fully formed pigs','trait');
INSERT INTO temp_domain VALUES ('0-1-5-23-287','Number of still born','trait');
INSERT INTO temp_domain VALUES ('0-1-5-23-159','mummified pigs','trait');
INSERT INTO temp_domain VALUES ('0-1-5-23-160','ovulation rate','trait');
INSERT INTO temp_domain VALUES ('0-1-5-24-161','weight of ovary','trait');
INSERT INTO temp_domain VALUES ('0-1-5-24-162','uterine capacity','trait');
INSERT INTO temp_domain VALUES ('0-1-5-24-163','uterine horn weight','trait');
INSERT INTO temp_domain VALUES ('0-1-5-24-164','uterine horn length','trait');
INSERT INTO temp_domain VALUES ('0-1-5-24-285','number of corpora lutea','trait');
INSERT INTO temp_domain VALUES ('0-1-5-24-165','male genital tract measurements','trait');
INSERT INTO temp_domain VALUES ('0-1-5-24-166','testies weight','trait');
INSERT INTO temp_domain VALUES ('0-1-5-26-167','Number of nipples','trait');
INSERT INTO temp_domain VALUES ('0-1-5-25-168','age at puberty','trait');
INSERT INTO temp_domain VALUES ('0-1-5-25-169','age at last farrowing','trait');
INSERT INTO temp_domain VALUES ('0-1-5-25-286','Gestation length','trait');
INSERT INTO temp_domain VALUES ('0-1-5-27-170','Plasma FSH concentration','trait');
INSERT INTO temp_domain VALUES ('0-1-1-1','fatness','type');
INSERT INTO temp_domain VALUES ('0-1-1-2','meat_color','type');
INSERT INTO temp_domain VALUES ('0-1-1-3','pH','type');
INSERT INTO temp_domain VALUES ('0-1-1-4','conductivity','type');
INSERT INTO temp_domain VALUES ('0-1-1-29','Enzyme activity','type');
INSERT INTO temp_domain VALUES ('0-1-1-30','stiffening','type');
INSERT INTO temp_domain VALUES ('0-1-1-5','texture','type');
INSERT INTO temp_domain VALUES ('0-1-1-6','chemical','type');
INSERT INTO temp_domain VALUES ('0-1-1-7','flavor','type');
INSERT INTO temp_domain VALUES ('0-1-1-8','odor','type');
INSERT INTO temp_domain VALUES ('0-1-1-9','Anatomy','type');
INSERT INTO temp_domain VALUES ('0-1-1-10','Fat composition','type');
INSERT INTO temp_domain VALUES ('0-1-2-11','pathogen','type');
INSERT INTO temp_domain VALUES ('0-1-2-12','Immune capacity','type');
INSERT INTO temp_domain VALUES ('0-1-2-13','Disease resistance','type');
INSERT INTO temp_domain VALUES ('0-1-3-14','Behavioral','type');
INSERT INTO temp_domain VALUES ('0-1-3-15','Coat_color','type');
INSERT INTO temp_domain VALUES ('0-1-3-16','conformation','type');
INSERT INTO temp_domain VALUES ('0-1-3-17','age','type');
INSERT INTO temp_domain VALUES ('0-1-3-18','defects','type');
INSERT INTO temp_domain VALUES ('0-1-4-19','feed intake','type');
INSERT INTO temp_domain VALUES ('0-1-4-28','digestive organ','type');
INSERT INTO temp_domain VALUES ('0-1-4-20','growth','type');
INSERT INTO temp_domain VALUES ('0-1-4-21','feed conversion','type');
INSERT INTO temp_domain VALUES ('0-1-5-23','Litter size','type');
INSERT INTO temp_domain VALUES ('0-1-5-24','Reproductive organ','type');
INSERT INTO temp_domain VALUES ('0-1-5-26','Reproductive organ','type');
INSERT INTO temp_domain VALUES ('0-1-5-25','Reproductive traits','type');
INSERT INTO temp_domain VALUES ('0-1-5-27','endocrine','type');
INSERT INTO temp_domain VALUES ('0','ATO','root');
INSERT INTO temp_domain VALUES ('0-1','sus scrofa','species');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
