
CREATE TABLE temp_trait(
  trait_id varchar(255) default NULL,
  trait_name varchar(255) default NULL,
  abbreviat varchar(255) default NULL,
  custom_name varchar(255) default NULL,
  trait_desc varchar(255) default NULL,
  measurement varchar(255) default NULL,
  scale_unit varchar(255) default NULL
);



INSERT INTO temp_trait VALUES ('0-1-1-1-1','abdominal fat','ABF','(null)','abdominal fat by weight','(null)','kg');
INSERT INTO temp_trait VALUES ('0-1-1-1-2','backfat (average) thickness','BFT','average backfat','Average backfat thickness among FRIB, LRIB, and LLUM.','Ruler','cm');
INSERT INTO temp_trait VALUES ('0-1-1-1-204','backfat (average) thickness','BFT','average backfat','Backfat thickness measured by ultrasound, average of several spots along the spin.','Ultrasound.','cm');
INSERT INTO temp_trait VALUES ('0-1-1-1-290','backfat (average) thickness','BFT','average backfat','Backfat thickness measured by Fat-O-Meater (FOM).',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-171','backfat at first rib','FRIBF','First rib backfat','Backfat thickness','Ruler','cm');
INSERT INTO temp_trait VALUES ('0-1-1-1-261','backfat at first rib (measured at 14 weeks of age)','14FRBF','(null)','Backfat thickness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-262','backfat at first rib (measured at 26 weeks of age)','26FRBF','(null)','Backfat thickness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-3','backfat above muscle dorsi','(null)','(null)','Backfat thickness','Ruler','cm');
INSERT INTO temp_trait VALUES ('0-1-1-1-4','backfat thickness at last rib','LRIBF','(null)','Backfat thickness','Ruler','cm');
INSERT INTO temp_trait VALUES ('0-1-1-1-291','backfat depth at last rib','LRIBFD',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-263','backfat at last rib (measured at 14 weeks of age)','14LRIBF','(null)','Backfat thickness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-264','backfat at last rib (measured at 26 weeks of age)','26LRIBF','(null)','Backfat thickness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-5','backfat at P2 position','(null)','(null)','Backfat thickness','Ruler','cm');
INSERT INTO temp_trait VALUES ('0-1-1-1-6','backfat at shoulder','BFSHO','(null)','Backfat thickness','Ruler','cm; mm');
INSERT INTO temp_trait VALUES ('0-1-1-1-7','backfat at tenth rib','10thribBF','Tenth rib backfat','Backfat thickness','Ruler','cm; mm');
INSERT INTO temp_trait VALUES ('0-1-1-1-8','backfat between 3th and 4th rib','34ribBF','(null)','Backfat thickness','Ruler','cm; mm');
INSERT INTO temp_trait VALUES ('0-1-1-1-306','backfat between 6th and 7th rib','67ribBF',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-9','backfat depth at max. mus. depth','(null)','(null)','Backfat thickness','Ruler','cm; mm');
INSERT INTO temp_trait VALUES ('0-1-1-1-10','backfat at last lumbar','LUMBF','Lumbar back fat','Backfat thickness','Ruler','cm; mm');
INSERT INTO temp_trait VALUES ('0-1-1-1-308','backfat between the last 3th and 4th lumbar','LUMBF',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-265','backfat at last lumbar (measured at 14 weeks of age)','14LUMBF','(null)','Backfat thickness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-266','backfat at last lumbar (measured at 26 weeks of age)','26LUMBF','(null)','Backfat thickness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-289','backfat at rump','BFTR','Rear backfat (RBT)','Backfat thickness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-11','backfat middle','BFM','(null)','Backfat thickness at the mid-point of the body length.','Ruler','cm; mm');
INSERT INTO temp_trait VALUES ('0-1-1-1-12','backfat side','BFS','(null)','Backfat thickness','Ruler','cm; mm');
INSERT INTO temp_trait VALUES ('0-1-1-1-188','backfat (13 weeks of age)','BF13w','(null)','Backfat thickness','Ruler',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-189','backfat (17 weeks of age)','BF17w','(null)','Backfat thickness','Ruler',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-190','backfat (22 weeks of age)','BF22w','(null)','Backfat thickness','Ruler',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-191','backfat (40 kg live weight)','BF40k','(null)','Backfat thickness','Ruler',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-192','backfat (60 kg live weight)','BF60k','(null)','Backfat thickness','Ruler',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-13','fat percentage in carcass','(null)','(null)','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-1-14','fat area',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-307','fat weight (total)','FW',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-15','intermuscular fat weight','IMF','(null)','(null)','(null)','g');
INSERT INTO temp_trait VALUES ('0-1-1-1-16','intramuscular fat percentage','IMF','intramuscular fat content','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-1-221','backfat weight','BFW','BFW','(null)','(null)','kg');
INSERT INTO temp_trait VALUES ('0-1-1-1-172','leaf fat weight','LFW','(null)','(null)','(null)','kg');
INSERT INTO temp_trait VALUES ('0-1-1-1-301','leaf fat percentage','LFP','(null)','leaf fat to carcass percent by weight',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-302','intestinal fat weight','CFW',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-303','intestinal fat percent','CFP','(null)','intestinal fat to carcass percent by weight',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-304','internal fat ratio','IFR',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-305','fat ratio (percentage)','FP',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-222','Percentage of backfat and leaf fat in carcass','BLFATP','(null)','Sum of subcutaenous body fat and internal fat expressed as percentage of carcass weight.','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-1-17','marbling','MARB','(null)','Small visible streaks of fat within a meat cut.','(null)','score');
INSERT INTO temp_trait VALUES ('0-1-1-1-18','residual fatty acids',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-19','side fat',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-20','subcutaneous fat depth','(null)','SUBCFAT','(null)','(null)','mm');
INSERT INTO temp_trait VALUES ('0-1-1-1-21','subcutaneous fat weight',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-22','sum of all fatty acids',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-1-23','total lipid','(null)','(null)','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-2-24','color a','mcolor','(null)','Objective color variable measured by colorimeter: Redness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-2-25','color b','mcolor','(null)','Objective color variable measured by colorimeter: Yelowness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-2-26','color L','mcolor','(null)','Objective color variable measured by colorimeter: Lightness',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-2-27','hue','mcolor',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-2-28','meat brightness','mcolor',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-2-29','light reflection','mcolor','Reflectance value','Various reflectance values are used to measure meat color, to quantitate myoglobin forms. It closely relates to what the eye and brain see.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-2-173','color score','mcolor','(null)','Objective scores.','38357','score');
INSERT INTO temp_trait VALUES ('0-1-1-2-201','Hematin pigmentation','mcolor','Hematin','Pigment content in meat.','(null)','ug/g');
INSERT INTO temp_trait VALUES ('0-1-1-3-30','pH 24 hours post mortem (loin)','pH',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-3-200','pH 24 hours post mortem (ham)','pH',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-3-31','pH 45 minutes post mortem','pH',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-3-311','pH for Biceps Femoris','pH',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-3-312','pH for Semispinalis Dorsi','pH',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-3-313','pH for Longissmus Dorsi','pH',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-4-32','conductivity 45 minutes post mortem',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-4-33','conductivity 24 hours post mortem',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-29-202','Creatine-phospho-kinase test','CK test',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-30-203','Rigor mortis','rigor','(null)','A process in which meat becomes rigid post mortum.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-34','average instron (star probe) force','(null)','(null)','(null)','(null)','Kg');
INSERT INTO temp_trait VALUES ('0-1-1-5-35','chew score','(null)','(null)','(null)','Objective scores.',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-36','cooking loss','(null)','(null)','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-5-37','drip loss','dripl','(null)','Water holding capacity predicted through drip loss in the longissimus muscle during 48 h. (%)',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-208','Number of white fibers','numfib','(null)','Fiber number on longgissimus dorsi between 13/14 ribs.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-209','Percentage of white fibers','percfiber','(null)','Fiber percentage on longgissimus dorsi between 13/14 ribs.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-210','Diameter of white fibers','dfiber','(null)','Fiber diameter on longgissimus dorsi between 13/14 ribs.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-211','R-value','r-value','(null)','R value is defined as the reflectance R8 of a meat sample so thick that further increases in thickness fail to change the reflectance; it describes the degree of desamination of adenosine',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-213','R-value / Diameter of white fibers','rdr',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-214','Lactate / Diameter of white fibers','ldr',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-38','fiber type 1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-39','fiber type 2 ratio',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-40','firmness',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-41','percent cooking loss',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-42','shear force',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-43','tenderness score','(null)','(null)','(null)','Objective scores.',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-5-44','water holding capacity','WHC','(null)','The ability of meat to retain its water during cutting, grinding, heating, pressing, etc','(null)','g');
INSERT INTO temp_trait VALUES ('0-1-1-5-297','Moisture Content','moist',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-6-45','androstenone, laboratory',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-6-46','average glycogen','GLY','(null)','(null)','mmol/g','umol/g');
INSERT INTO temp_trait VALUES ('0-1-1-6-47','average glycolytic potential','GLYPO','(null)','(null)','mmol/g','umol/g');
INSERT INTO temp_trait VALUES ('0-1-1-6-48','average lactate','LACT','(null)','(null)','mmol/g','umol/g');
INSERT INTO temp_trait VALUES ('0-1-1-6-49','cholesterol','(null)','(null)','Blood cholesterol concentration','(null)','mg/dl');
INSERT INTO temp_trait VALUES ('0-1-1-6-50','indole, laboratory',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-6-52','muscle moisture percentage',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-6-53','muscle protein percentage',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-6-54','pork flavour in fat',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-6-55','pork flavour in lean',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-6-56','skatole, laboratory',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-57','androstenone, taste panel',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-58','skatole, taste panel',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-59','subjective abnormal flavour in fat',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-60','subjective abnormal flavour in lean',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-61','subjective boar flavor in fat',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-62','subjective boar flavor in lean',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-63','subjective chew score','(null)','(null)','(null)','Objective scores.',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-64','subjective flavor score','(null)','(null)','(null)','Objective scores.',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-65','subjective juiciness score','(null)','(null)','(null)','Objective scores.',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-66','subjective pork flavor in fat',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-67','subjective pork flavor in lean',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-68','subjective tenderness score','(null)','(null)','(null)','Objective scores.',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-174','subjective off-flavor score','(null)','off-flavor','Any flavor that is not associated with normal pork flavor.','Objective scores.',NULL);
INSERT INTO temp_trait VALUES ('0-1-1-7-175','intensity taste','itaste',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-8-69','subjective abnormal odor',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-8-70','subjective overall acceptibility score',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-8-71','subjective pork odour',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-8-176','smell intensity','ISMEL',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-8-177','smell intensity - fat','ISMELF',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-8-178','Sub-acid smell','SASML',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-72','body mass index','BMI','(null)','BMI = weight at slaughter / carcass length','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-73','bone weight',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-310','bone percent','BP',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-247','bone/lean meat ratio in ham','BLR','(null)','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-248','Lean meat + bone in ham + back','LBp','(null)','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-281','Lean mass (weight)','leanwt','(null)','(null)','(null)','kg');
INSERT INTO temp_trait VALUES ('0-1-1-9-249','Lean meat + bone in back','Lbpback','(null)','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-279','Backfat percentage','BFP','(null)','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-280','Fat-cut percentage','FATCP','(null)','carcass fat percentage','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-74','belly weight','bellywt',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-288','belly percentage','bellyp','(null)','= 4belly weight / carcass weight',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-75','carcass length','crcl','(null)','(null)','crcl','cm');
INSERT INTO temp_trait VALUES ('0-1-1-9-76','carcass weight (cold)','CCWT',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-293','Carcass yield','CYIELD',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-283','carcass fat free weight','CWNOFAT',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-77','hot carcass weight','(null)','HCWT',NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-223','dressing percentage','dressing','dressing','The percentage of the live animal that ends up as carcass','Carcass Weight / Live Weight X 100','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-78','diaphragm weight',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-79','eye muscle depth','(null)','(null)','Between the 3rd and 4th rib',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-80','Feet weight','feetwt',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-81','foreloin weight post-dissection',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-82','foreloin weight pre-dissection',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-83','head weight','headwt',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-84','lean percentage','leanp','Meat percentage','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-277','ham percent','hamp','(null)','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-85','lean thickness between 3th and 4th rib',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-86','loin eye area','LEA','longissmus muscle area','(null)','loineyea','(cm) square');
INSERT INTO temp_trait VALUES ('0-1-1-9-295','Longissimus muscle length','loinlength',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-87','muscle + diaphragm weight',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-88','muscle weight','leanwt',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-215','Loin weight','loinwt','(null)','(null)','(null)','kg');
INSERT INTO temp_trait VALUES ('0-1-1-9-278','Loin percent','loinp','(null)','(null)','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-216','Ham weight','hamwt','(null)','(null)','(null)','kg');
INSERT INTO temp_trait VALUES ('0-1-1-9-217','Estimated carcass lean content','ECLC','lean content','(null)','ECLC =-3 .539 +75 .1 (proportion of ham) +121.6 (proportion of loin) -61 (proportion of backfat) -45.3 (proportion of leaf fat) +32.8 (proportion of belly)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-218','Loin and ham percentage in carcass','LHP','lean percentage','Percentage portion of Loin and Ham weight over carcass weight','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-9-219','Shoulder weight','SHOUWT','(null)','(null)','(null)','kg');
INSERT INTO temp_trait VALUES ('0-1-1-9-220','Loin muscle depth','Lmdepth','loin height','(null)','Usually ultrasound; at the last ribs.','mm');
INSERT INTO temp_trait VALUES ('0-1-1-9-296','Loin and belly cut','LBCUT',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-89','skin weight','SW',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-309','skin percentage','SP',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-198','skin thickness','(null)','(null)','Skin thickness on the back, at the mid-point of body length.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-90','Trimmed whole-sale product / live weight','(null)','twplwt','Trimmed whole-sale product adjusted to a constant live weight',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-91','Trimmed whole-sale product / carcass weight','(null)','twpcwt','Trimmed whole-sale product adjusted to a constant carcass weight',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-9-282','Heart weight','HWT','(null)','(null)','(null)','kg');
INSERT INTO temp_trait VALUES ('0-1-1-10-92','fat androstenone level','FANDRO','(null)','androstenone level measured at slaughter',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-10-267','fat androstenone level at 100 days of age','100FANDRO',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-10-268','fat androstenone level at 120 days of age','120FANDRO',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-10-269','fat androstenone level at 140 days of age','140FANDRO',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-10-270','fat androstenone level at 160 days of age','160FANDRO',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-10-93','Linoleic acid percentage','FA-C18:2','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-94','heptadecanoic acid percentage','(null)','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-229','Linolenic acid percentage','FA-C18:3','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-230','Myristic acid percentage','FA-C14:0','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-231','Palmitic acid percentage','FA-C16:0','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-232','Palmitoleic acid percentage','FA-C16:1','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-179','Heptadecanoic acid percentage','FA-C17:0','Fatty acid composition','Measured in backfat',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-10-250','Stearic acid percentage','FA-C18:0','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-251','Oleic acid percentage','FA-C18:1n-9','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-252','7-Octadecenoic acid percentage','FA-C18:1n-7','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-253','Eicosenoic acid percentage','FA-C20:1','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-254','Eicosadienoic acid percentage','FA-C20:2','Fatty acid composition','Measured in backfat','(null)','%');
INSERT INTO temp_trait VALUES ('0-1-1-10-233','Average chain length','FA-ACL',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-10-234','Double-bond index','FA-DBI',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-10-235','Unsaturated index','FA-UI',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-1-10-236','Peroxidability index','FA-PI',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-11-95','Salmonella count in feces day 1 post infection',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-11-96','Salmonella count in feces day 7 post infection',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-11-97','Salmonella count in liver','SCL','','','','');
INSERT INTO temp_trait VALUES ('0-1-2-11-98','Salmonella count in spleen',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-12-99','number of leucocytes','WBC','White blood cells','Count of white blood cells','With cello-scope','cpm');
INSERT INTO temp_trait VALUES ('0-1-2-12-100','mitogen-induced proliferation','(null)','(null)','(null)','(null)','cpm');
INSERT INTO temp_trait VALUES ('0-1-2-12-271','PWM-induced proliferation','PWM','(null)','(null)','(null)','cpm');
INSERT INTO temp_trait VALUES ('0-1-2-12-272','conA-induced proliferation','conA','(null)','(null)','(null)','cpm');
INSERT INTO temp_trait VALUES ('0-1-2-12-273','spontenous proliferation','spont','(null)','(null)','(null)','cpm');
INSERT INTO temp_trait VALUES ('0-1-2-12-101','pre/post-vaccination levels of IgG to K88 antigen',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-12-102','specific IgG response to E. coli O149 antigen',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-12-103','post-stress mitogen induced IL-2 activity',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-12-104','stress induced neutrophils numbers alteration',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-12-105','stress induced leukocyte proliferation.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-13-106','resistance to E.coli K88 infection','K88R',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-13-274','Anti-K88 E.coli IgG levels','K88Ab','(null)','Natural IgG Ab levels against K88 E.coli',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-13-275','Anti-O149 E.coli IgG levels','0149Ab','(null)','Natural IgG Ab levels against O149 E.coli',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-13-276','Anti-O149 E.coli IgG level response','0149AbR','(null)','IgG response to O149 E.coli',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-13-224','Small intestinal Escherichia coli F18 receptor','ECF18R',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-2-13-51','resistance to psuedorabies virus infection',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-14-107','ACTH basal level','ACTH1','(null)','Basal Adrenocorticotropic Hormone (ACTH) levels','from EDTH treated blood','pg/ml');
INSERT INTO temp_trait VALUES ('0-1-3-14-237','ACTH response to stress','ACTH2','(null)','Post stress Adrenocorticotropic Hormone (ACTH) levels','from EDTH treated blood','pg/ml');
INSERT INTO temp_trait VALUES ('0-1-3-14-238','ACTH response to stress','dACTH','(null)','Adrenocorticotropic Hormone (ACTH) variations','from EDTH treated blood','pg/ml');
INSERT INTO temp_trait VALUES ('0-1-3-14-108','Basal cortisol levels','CORT1','(null)','Basal cortisol levels','from EDTH treated blood','pg/ml');
INSERT INTO temp_trait VALUES ('0-1-3-14-239','post-stress cortisol levels','CORT2','(null)','Post stress cortisol levels','from EDTH treated blood','pg/ml');
INSERT INTO temp_trait VALUES ('0-1-3-14-240','post-stress cortisol levels','dCORT','(null)','Cortisol level variations','from EDTH treated blood','g/ml');
INSERT INTO temp_trait VALUES ('0-1-3-14-241','Basal glucose levels','GLU1','Glycemia','(null)','from EDTH treated blood','g/ml');
INSERT INTO temp_trait VALUES ('0-1-3-14-242','Glucose level response to stress','GLU2','Glycemia','(null)','from EDTH treated blood','g/ml');
INSERT INTO temp_trait VALUES ('0-1-3-14-243','Glucose level variations','dGLU','Glycemia','(null)','from EDTH treated blood','g/ml');
INSERT INTO temp_trait VALUES ('0-1-3-14-244','Locomotion','LOC','(null)','Number of test areana sections entered during stress.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-14-245','Exploration','EXPL','(null)','Time spent rooting, sniffing the floor or the sides of the test arena during test period.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-14-109','neuroendocrine responses',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-15-110','black vs white color','CC',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-15-111','spots','CC',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-112','body length',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-294','thoracic vertebra number','tvnum',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-197','total vertebra number','vnum','(null)','sum of thoracic and lumbar vertebra numbers.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-246','vertebra distance','vdist','Distance between spine bones.','(null)','(null)','cm');
INSERT INTO temp_trait VALUES ('0-1-3-16-113','claws length front inside',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-114','claws length front outside',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-115','claws length hind inside',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-116','claws length hind outside',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-117','feet and legs score','(null)','(null)','(null)','Objective scores.',NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-118','feet score front',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-119','feet score rear',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-120','hair (amount)',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-121','height',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-122','joint abnormalities',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-123','joint leasions',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-124','leg length',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-125','leg pastern front',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-126','leg pastern hind',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-127','leg score front',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-128','leg score hind',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-129','leg set view',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-130','leg torsion front',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-131','leg torsion hind',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-132','legs angularity front',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-133','legs angularity hind',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-292','Circumference of cannon bone','ccannon',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-134','femur dimensions',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-135','osteochondrosis',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-136','lob ear',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-137','nose score','(null)','(null)','(null)','Objective scores.',NULL);
INSERT INTO temp_trait VALUES ('0-1-3-16-138','swelling of joints',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-17-139','longevity (sow)',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-18-140','scrotal hernia',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-3-18-141','rhinitis',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-19-142','feed intake 35 to 55 kg','(null)','(null)','(null)','(null)','kg/day');
INSERT INTO temp_trait VALUES ('0-1-4-19-143','feed intake 55 to 80 kg','(null)','(null)','(null)','(null)','kg/day');
INSERT INTO temp_trait VALUES ('0-1-4-28-195','length of small intestine','LSI','(null)','(null)','(null)','cm');
INSERT INTO temp_trait VALUES ('0-1-4-20-144','average daily gain','ADG','(null)','(null)','(null)','kg/day');
INSERT INTO temp_trait VALUES ('0-1-4-20-145','average daily gain 35 to 55 kg','ADG','(null)','ADG during \"grower\" period.','(null)','kg/day');
INSERT INTO temp_trait VALUES ('0-1-4-20-146','average daily gain 55 to 80 kg','ADG','(null)','ADG during \"finishing\" period.','(null)','kg/day');
INSERT INTO temp_trait VALUES ('0-1-4-20-205','average daily gain weaning to 25 kg','ADG','EGR','Early ADG from weaning (5.5kg) to 25 kg (nursery).','(null)','g/day');
INSERT INTO temp_trait VALUES ('0-1-4-20-225','average daily gain weaning to 55 kg','ADG','(null)','ADG during nursery and growing period (between weaning and slaughter).',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-206','average daily gain 25 to 90 kg','ADG','TGR','Test ADG from 25 kg to 90 kg.','(null)','g/day');
INSERT INTO temp_trait VALUES ('0-1-4-20-207','average daily gain during the entire life.','ADG','LGR','Life time growth ADG.','(null)','g/day');
INSERT INTO temp_trait VALUES ('0-1-4-20-147','average daily gain birth to end of test','ADG','(null)','ADG during Birth to finishing (55 kg)','(null)','kg/day');
INSERT INTO temp_trait VALUES ('0-1-4-20-193','average daily gain birth to 30 kg','ADG',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-194','average daily gain birth to 70 kg','ADG',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-148','average daily gain on weaning','ADG','(null)','average daily gain birth to weaning (5.5kg)','(null)','kg/day');
INSERT INTO temp_trait VALUES ('0-1-4-20-149','average daily gain on test','ADG','(null)','average daily gain during the \"test period\".','(null)','kg/day');
INSERT INTO temp_trait VALUES ('0-1-4-20-185','average daily gain (birth to 3 weeks)','ADG','(null)','ADG during birth to weaning','(null)','(null)');
INSERT INTO temp_trait VALUES ('0-1-4-20-226','average daily gain (3 to 5 weeks)','ADG',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-227','average daily gain (5 to 7 weeks)','ADG',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-228','average daily gain (7 to 9 weeks)','ADG',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-186','average daily gain (3-10 weeks)','ADG','(null)','ADG during Nursery period',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-196','average daily gain (4-13 weeks)','ADG','(null)','ADG during Growing period',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-187','average daily gain (10-22 weeks)','ADG','fattening ADG','ADG during Finishing period','(null)','(null)');
INSERT INTO temp_trait VALUES ('0-1-4-20-259','average daily gain (8-18 weeks)','ADG; EDG',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-260','average daily gain (18-26 weeks)','ADG; LDG',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-298','average daily gain (birth-60 days)','ADG',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-299','average daily gain (60-160 days)','ADG',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-153','body weight at birth','BWt','Birth weight','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-154','body weight at slaughter','endWT','(null)','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-284','Age at slaughter','endage',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-155','body weight at 16 days','16dWt','(null)','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-180','body weight at 3 weeks of age','21dWt','(null)','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-199','body weight at weaning','WWT','weaning weight','pigs are normally weaned at 42 days of age.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-256','body weight at 4 weeks of age','Wt',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-257','body weight at 8 weeks of age','Wt',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-181','body weight at 10 weeks of age','Wt','(null)','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-182','body weight at 13 weeks of age','Wt','(null)','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-183','body weight at 17 weeks of age','Wt','(null)','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-184','body weight at 22 weeks of age','Wt','(null)','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-255','body weight at 25 weeks of age','Wt','Live weight','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-258','body weight at 26 weeks of age','Wt','Finishing weight','Measured live',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-20-300','body weight at 60 days of age','Wt',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-21-150','feed conversion ratio',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-21-151','feed conversion ratio 35 to 55 kg',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-4-21-152','feed conversion ratio 55 to 80 kg',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-23-156','total number born','LS','Litter size',NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-23-157','total number born alive','NBL','prenatal survival',NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-23-158','fully formed pigs','NFF',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-23-287','Number of still born','NSB',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-23-159','mummified pigs',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-23-160','ovulation rate','OVRATE','(null)','Measurement taken 7 to 14 d following first postweaning estrus.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-24-161','weight of ovary','OW',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-24-162','uterine capacity','UC',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-24-163','uterine horn weight',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-24-164','uterine horn length','UL',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-24-285','number of corpora lutea','NCL',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-24-165','male genital tract measurements',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-24-166','testies weight','testiwt','Testicular weight',NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-26-167','Number of nipples','TNUM','teat number','The sum of left teats and right teats.',NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-25-168','age at puberty','AGEP',NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-25-169','age at last farrowing',NULL,NULL,NULL,NULL,NULL);
INSERT INTO temp_trait VALUES ('0-1-5-25-286','Gestation length','GEST','Gestation length','Number of days the sow is pregnant','(null)','days');
INSERT INTO temp_trait VALUES ('0-1-5-27-170','Plasma FSH concentration','FSH',NULL,NULL,NULL,NULL);
